### ISSUE TITLE
Use a better icon for PortableApps folder

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#1]
Hi @JohnTHaller 
Please use a better icon for the PortableApps folder. (like Windows 11 folder icon)
The current icon is very old.
Please download [WindowsFolderIcons.zip](https://github.com/PortableApps/Platform/files/7333566/WindowsFolderIcons.zip)

# Preview:
![256](https://user-images.githubusercontent.com/23485114/137040426-ef1cafae-47d6-496f-bba2-697f35f2a321.png)
![064](https://user-images.githubusercontent.com/23485114/137040428-842fc03d-8e0b-403d-9863-e338a1e7cf5f.png)
![048](https://user-images.githubusercontent.com/23485114/137040430-4c4f78db-f6b4-4695-92fe-e691337366a7.png)
![040](https://user-images.githubusercontent.com/23485114/137040431-08547097-1c3a-403a-a0a0-a589cd915389.png)
![032](https://user-images.githubusercontent.com/23485114/137040432-3415bbd4-3a8a-4a00-8f50-084d5cd5ee38.png)
![024](https://user-images.githubusercontent.com/23485114/137040436-b72d35a0-14e8-4449-8a32-06b5b777c1f3.png)
![020](https://user-images.githubusercontent.com/23485114/137040437-ff0b0550-3f67-47e7-8317-8fbc45b1d8e5.png)
![016](https://user-images.githubusercontent.com/23485114/137040441-4bc85428-7e8a-40d6-b9b8-d673426838c0.png)

**Comment by JohnTHaller** [comment]
Coming Soon... I did a quick update to the platform's category folders but ran out of time to get the folder icons for PortableApps, Documents, etc folders on the drive itself. I'm working on new ones patterned after the Windows 11 style like yours is for an upcoming release.

**Comment by JohnTHaller** [comment]
Updated icons for the PortableApps, Documents, Music, Pictures, and Video folders with all relevant sizes for all versions of Windows have been included in the 19.1 release.

**Comment by xmha97** [comment]
Thanks 😍🙏
![image](https://user-images.githubusercontent.com/23485114/139702955-3bd15df2-8d8c-40af-a17b-09904c59b0a6.png)

**Comment by xmha97** [comment]
Hello @JohnTHaller
Please send me your icons in SVG format.
I want to create some custom folders.
For example, a folder for podcasts or a folder for fonts.
Eventually, I will put all the icons I created in a repository for everyone to use, such as the repository below:
https://github.com/FadeMind/W-ICO
Thanks.

**Comment by JohnTHaller** [comment]
The base folder icon is a simplified version of the Oxygen icon set folder icon. I've attached a zip of the svg and the open and closed PNGs. It's licensed under the GPL 3 or later and the LGPL 3 or later as with the Oxygen set.

[folder.zip](https://github.com/PortableApps/Platform/files/7541220/folder.zip)
![folder](https://user-images.githubusercontent.com/8020860/141842337-71e08402-b23b-414f-b515-58fefa833ae5.png)
![folder-open](https://user-images.githubusercontent.com/8020860/141842350-bd84e5f3-ed9d-47df-b0d4-4c39dd87f08f.png)
