### ISSUE TITLE
Use Large Fonts

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#10]
# Why is this option disabled?
- Use Large Fonts

![image](https://user-images.githubusercontent.com/23485114/155744915-ca442063-4cab-4d6d-b71d-43d176fc92c9.png)

# My Display Info
![image](https://user-images.githubusercontent.com/23485114/155745159-f4c8d937-b778-46ee-a025-3293c18f1ff3.png)

**Comment by JohnTHaller** [comment]
If you have Windows scaling on it is disabled because the font size will exceed the display areas.
