### ISSUE TITLE
Can't see SSD flash on installer

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#12]
Hi, I can't see the SSD flash drives on the installer.
Please show all USB drives.
![image](https://user-images.githubusercontent.com/23485114/169769937-b24182df-ed01-48b9-9815-f2425f41ef3b.png)
![image](https://mspoweruser.com/wp-content/uploads/2017/01/SanDisk-Extreme-PRO-USB-3.1-FlashDrive.png)

**Comment by JohnTHaller** [comment]
If the drive doesn't present itself as a removable device to Windows, it won't show up in that list. Many external hard drives/SSDs do not present as such. You generally won't see an eject option when you right-click them in Explorer either.
