### ISSUE TITLE
Display apps as a grid

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#2]
Display apps as a grid (instead of a list), like the Windows 10 & 11 start menu.
<img width="459" alt="Untitled" src="https://user-images.githubusercontent.com/23485114/139703154-66b0fa5e-09e8-4b2a-9d24-66a50ad429a7.png">

**Comment by JohnTHaller** [comment]
At some point the platform will be rewritten to support this, but not right now.

**Comment by xmha97** [comment]
> At some point the platform will be rewritten to support this, but not right now.

Ok, thanks.
