### ISSUE TITLE
Mp3tagPortable

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#4]
Hi, I need the portable version of the Mp3tag app.
https://www.mp3tag.de/en/
Please add this:
https://portableapps.com/node/18890
Thanks.

**Comment by GordCaswell** [comment]
Unfortunately, we are unable to release Mp3tag as an official application, as we have been denied permission to do so by the developer.

See here: https://portableapps.com/comment/228014#comment-228014

**Comment by JohnTHaller** [comment]
I emailed the author again referencing my previous inquiry in 2012. Perhaps they'll reconsider. For other app requests, please us the Request Apps forum: https://portableapps.com/forums/general/request_apps
