### ISSUE TITLE
SimplenotePortable

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#5]
Now I see you created an electron portable app:
https://portableapps.com/apps/music_video/lossless-cut-portable

So, please make the portable version of Simplenote.
Simplenote is one of the best note-taking apps and it's free and open-source.
https://github.com/Automattic/simplenote-electron
![image](https://user-images.githubusercontent.com/23485114/151661600-e9313151-0fb6-4a87-b1c2-01fd77050acb.png)
https://github.com/Automattic/simplenote-electron/issues/3068

**Comment by JohnTHaller** [comment]
Please request apps within the Request Apps forums so that all developers and volunteers. This is only for PortableApps.com Platform issues. https://portableapps.com/forums/general/request_apps

**Comment by xmha97** [comment]
OK, sorry for that.
https://portableapps.com/node/65616

**Comment by xmha97** [comment]
Also, see this:
https://github.com/xmha97/PortableApps/releases/tag/Simplenote-v2.21
