### ISSUE TITLE
An Environment Variable (for the user, not machine)

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#6]
Please add a temporary environment variable when PortableAppsPlatform is running.
For example `%PortableApps_Home%`=F:\\
![image](https://user-images.githubusercontent.com/23485114/151753714-8ed47d15-b99a-4320-8aba-559dfbc995f7.png)
`%PortableApps_Home%`\PortableApps
`%PortableApps_Home%`\Documents

**Comment by xmha97** [comment]
Perhaps this feature does not look good, but it is necessary for some portable apps.
For example Firefox and Thunderbird:
![image](https://user-images.githubusercontent.com/23485114/151754576-a748d759-70a7-4acb-9ac5-0a2429b0e390.png)
I can't use `..\..\..\Documents`
and I want to use this: `%PortableApps_Home%\Documents`

**Comment by JohnTHaller** [comment]
For this scenario, set it to a full directory. The ThunderbirdPortable.exe launcher will automatically adjust the path. All paths within prefs.js are automatically adjusted in Thunderbird, SeaMonkey, and Firefox.

Additional environment variables are planned.

**Comment by xmha97** [comment]
I do not think that the FirefoxPortable.exe launcher adjusts the path.

https://user-images.githubusercontent.com/23485114/151841130-4f43db73-fead-4397-91be-e67429ff9b23.mp4

Thank you for planning additional environmental variables.

**Comment by JohnTHaller** [comment]
It looks like Firefox's launcher only does drive letter replacement of the Download directory at the moment (so it'd be fine on an external drive moving around or a local drive staying put but not in a synced cloud folder to PCs with different logins). I'll upgrade that to full paths in the next release.

**Comment by xmha97** [comment]
Please upgrade Thunderbird's launcher to full paths as well.

**Comment by JohnTHaller** [comment]
> Please upgrade Thunderbird's launcher to full paths as well.

All 3 of the Mozilla launchers will be. You can follow along in this bug here: https://portableapps.com/node/65688

**Comment by xmha97** [comment]
Thanks, I will try the test version.

**Comment by xmha97** [comment]
Hi John,
I realized that the FreeCommander XE Portable launcher is not fully portablizing the start path. 
![image](https://user-images.githubusercontent.com/23485114/153863167-968de70b-8efc-44d3-81a5-3418ef5cbb4e.png)
Please fix it.

**Comment by JohnTHaller** [comment]
PortableApps.comRoot and PortableApps.comApps environment variables have been added in today's 21.0 release. They map to the root of the install containing Start.exe and the PortableApps directory respectively.

**Comment by xmha97** [comment]
Now I using PA Platform v21.0
![image](https://user-images.githubusercontent.com/23485114/156886442-ee3e4547-e371-4f3f-a2bd-994521494d53.png)

As you can see, the platform is running but the following variables do not work:
`%PortableApps.comApps%` and `%PortableApps.comRoot%`
![image](https://user-images.githubusercontent.com/23485114/156886530-d1bf4157-b851-48cf-b346-43d45ab4dd41.png)

All my environment variable:
![image](https://user-images.githubusercontent.com/23485114/156886686-a98bd7db-8012-4d61-91c9-64dc1507d136.png)

**Comment by JohnTHaller** [comment]
Not user/system level. The variables are only for the PA.c Process and processes launched from it. We won't set user-level variables outside the platform.

Note that the variables currently contain the wrong entries which will be fixed in 21.1

**Comment by JohnTHaller** [comment]
I'm finishing up a 21.0.1 release (not 21.1) to address the few bugs that showed up quickly in 21.0. I've added a manual setting for you to set these new environment variables to the whole user while running. It'll be off by default. But, in the PortableAppsMenu.ini settings file you'll see a new entry once you upgrade:

[SystemIntegration]
SystemWideEnvironmentVariables=False

Setting that to True will cause the variables to be set at the user level and all open windows notified of the change.

**Comment by xmha97** [comment]
Thanks.
