### ISSUE TITLE
Add the "Try Again" button

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#7]
@JohnTHaller Please add the `Try Again` button on the exit dialog.

![image](https://user-images.githubusercontent.com/23485114/153149994-198b56e9-d082-420d-962a-de6e9bf72bd8.png)

**Comment by JohnTHaller** [comment]
Note: Please don't tag me directly in bug reports and feature requests

**Comment by JohnTHaller** [comment]
As the user can click close again and this would require a heavy rewrite of FormClose (or using a GoTo) and I don't see myself having the bandwidth for this vs keeping the project afloat, I'm going to call this a WONTFIX.

**Comment by JohnTHaller** [comment]
Scratch that. I'll hold my nose and use a GoTo for now so users get it.

**Comment by JohnTHaller** [comment]
This has been added to my internal code and will be in the PA.c Platform 21.0 release. It will be OK/Cancel. Try again as a solo string may be localized in our 68+ languages later on.

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/156886349-d0e0756f-ca8d-459d-aefe-06dd73332ffe.png)
Thanks.
