### ISSUE TITLE
The apps icons will not load in ReactOS

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#8]
The apps icons will not load on ReactOS (Windows 2003)
![image](https://user-images.githubusercontent.com/23485114/154785627-3cfa77ea-6abe-4ebb-9094-ba8fe1fbbcfd.png)

**Comment by JohnTHaller** [comment]
We don't support officially support ReactOS. Although it usually works, it sometimes does something like this. With no rhyme or reason. It was working on Jan 7, 2022:
![ReactOS](https://user-images.githubusercontent.com/8020860/154790435-3ff21c52-b2a3-4e3a-906c-7dba7617833d.png)

But now it is not. Same version of ReactOS. No changes to our code that displays the apps. Same Delphi compiler. But now it's not. Platform 19.2 displays the Opera icon but not Opera GX in ReactOS. Why? No idea. They have the same icon sizes and formats in the ICO.

If you can determine what's up and a fix, I'm happy to implement it. But it's not something I'm going to explore and troubleshoot at present.
