### ISSUE TITLE
Some small ideas

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Platform#9]
Hi,
I have some ideas for the PortableApps Platform.
I do not think it is time-consuming to add them.

![image](https://user-images.githubusercontent.com/23485114/155740913-6a9199d9-eb8f-4608-9458-1f793d4ac2f0.png)
Also add a dark context menu

![image](https://user-images.githubusercontent.com/23485114/155742745-279d9ff2-d11e-4985-9d17-ae4819b930cb.png)

Thanks.

**Comment by JohnTHaller** [comment]
It's favorite on purpose as it also shows in Favorites in the tray icon. Won't be changing this.

Clear Data will actually be called Reset App and will be implemented at some point as time and translation permits. It's already in the list, which is the main location for bug reports, feature requests, etc: https://portableapps.com/node/28593

Dark submenus don't work properly in Drupal at the moment. It just uses Windows colors mostly. This is unlikely to change without a rewrite.

I don't plan on adding the ability to terminate apps as it can lead to data loss.

Monitoring running apps would require constant polling of the TProcesses list and updating of the menu. I don't see a use case for this. If Windows itself did it in the Start menu I might consider it.
